### PR TITLE
Change all deprecate mcrypt_encrypt and mcrypt_dencrypt to openssl_en…

### PR DESCRIPTION
**Pull request by amanfrinati**
To improve the compatibility with PHP 7.0, I edited all deprecate mcrypt_encrypt and mcrypt_dencrypt with openssl_encrypt and openssl_dencrypt.
I added a result message to the event settings page when user save settings.

### CODE REVIEW

**Comment by glynhudson** [comment]
Thanks 👍

**Comment by elyobelyob** [comment]
Wow, are people still using this?!

**Comment by amanfrinati** [comment]
Oh yeah,
I can't find other way in emoncms to send mail alert when my feed changed.
I'm still using a custom version of emoncms 8.5..

Il giorno gio 26 ott 2017 alle ore 15:42 elyobelyob <
notifications@github.com> ha scritto:

> Wow, are people still using this?!
>

**Comment by elyobelyob** [comment]
I'd use 'publish to MQTT' and then have an MQTT node in node-red awaiting
for that message and acting upon it.

There's definitely got to be a better way than that old event module I gave
up developing 2 years ago!

Thanks though, made me smile that someone still uses it - not a complete
waste of a Christmas break a few years back ... :)

**Comment by amanfrinati** [comment]
Ahahah, no problem! Great work on Xmas break ;)

Il giorno gio 26 ott 2017 alle ore 16:15 elyobelyob <
notifications@github.com> ha scritto:

**Pull request merged**
